packages:
  - 'packages/*'
  - 'tests'

catalog:
  # Shared development dependencies
  "@types/node": "^20.10.0"
  "typescript": "^5.3.0"
  "vitest": "^1.0.0"
  "@biomejs/biome": "^1.5.0"

  # Shared production dependencies
  "acorn": "^8.11.0"
  "acorn-jsx": "^5.3.2"
  "chalk": "^5.3.0"
  "chokidar": "^3.5.3"
  "commander": "^11.0.0"
  "gray-matter": "^4.0.3"
  "@rollup/pluginutils": "^5.0.0"
  "astro": "^4.0.0"
  "vite": "^5.0.0"
